name: Trigger Netlify Daily Build

on:
  schedule:
    - cron: '0 21 * * *' # This will run the action every day at 09:00 UTC
  workflow_dispatch: # This allows the workflow to be run manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Netlify Daily Build
      run: |
        curl -X POST -d {} https://api.netlify.com/build_hooks/${{ secrets.NETLIFY_DAILY_BUILD }}
